// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cymqslbkwhutbmshlnvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5bXFzbGJrd2h1dGJtc2hsbnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODUwODYsImV4cCI6MjA2NzY2MTA4Nn0.SQWR6OXnI8pknYamQ7IW9rM9Qh5-wZdi1FzDw-N7k3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});